const SAVE_KEY = 'statussim.save.v1';
const root = document.getElementById('root');
const uid = (p = 'id') => `${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
const now = () => new Date().toISOString();
const clamp = (n, min, max) => Math.max(min, Math.min(max, Number(n) || 0));
const pick = (a) => a[Math.floor(Math.random() * a.length)];
const sample = (a, n) => [...a].sort(() => Math.random() - 0.5).slice(0, n);
const initials = (name) => `https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent(name || 'StatusSim')}&backgroundColor=111827,312e81,7f1d1d`;
const esc = (v) => String(v ?? '').replace(/[&<>'"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c]));
const splitList = (value) => String(value || '').split(',').map((x) => x.trim()).filter(Boolean);

const AI_SYSTEM_PROMPT = 'You are the simulation engine for a fictional single-player social media life simulator. You generate realistic in-universe reactions to the player’s actions. Stay consistent with the world rules, character personalities, relationship scores, and timeline memory. Do not use real copyrighted characters unless the user created them. Do not make every character love the player. Generate mixed public opinion. Respect the world’s language style. Keep consequences believable. Return only valid JSON in the requested schema.';
const baseStats = { followers: 240, following: 83, reputation: 42, influence: 18, drama: 12, charm: 45, authenticity: 55, controversy: 8, mystery: 30 };
const postTypes = ['Normal post', 'Image-style post', 'Poll', 'Quote post', 'Reply', 'Apology', 'Callout', 'Flirt post', 'Confession', 'Announcement', 'Cryptic post', 'Private close-friends post'];
const tabs = [['feed', '⌂', 'Feed'], ['post', '✎', 'Post'], ['dms', '✉', 'DMs'], ['notifications', '●', 'Alerts'], ['characters', '☷', 'Cast'], ['profile', '◉', 'Profile'], ['memory', '▣', 'Memory'], ['worlds', '◎', 'Worlds'], ['settings', '⚙', 'Settings']];

function character(name, role, personality, extras = {}) {
  const handle = name.toLowerCase().replace(/[^a-z0-9]+/g, '').slice(0, 16);
  return { id: uid('char'), name, username: `@${handle}`, avatar: extras.avatar || initials(name), role, personality,
    publicImage: extras.publicImage || pick(['polished but guarded', 'warm fan favorite', 'mysterious social climber', 'competitive prodigy']),
    privateInsecurity: extras.privateInsecurity || pick(['being forgotten', 'not being talented enough', 'losing control of the narrative', 'trusting the wrong person']),
    likes: extras.likes || ['loyalty', 'wit', 'bold public moments'], dislikes: extras.dislikes || ['clout chasing', 'public betrayal', 'messy receipts'],
    relationshipScore: extras.relationshipScore ?? Math.floor(Math.random() * 41) - 10, relationshipStatus: extras.relationshipStatus || 'Stranger',
    opinionOfPlayer: extras.opinionOfPlayer || 'Waiting to see if the player is authentic or just chasing attention.',
    postingStyle: extras.postingStyle || 'sharp, image-conscious, and specific to the world slang', dmStyle: extras.dmStyle || 'more vulnerable and direct than public posts',
    dramaTriggers: extras.dramaTriggers || ['being subtweeted', 'alliance pressure', 'rumors'], allies: extras.allies || [], enemies: extras.enemies || [], approved: true };
}
const blueprints = [
  ['Arcane Academy', 'Elite magic school drama where honors, secrets, and spellcraft status collide.', 'Contemporary magical academy', 'Academic, mysterious, competitive; house rivalries and veiled threats.', ['Aether House', 'Obsidian House', 'Faculty Circle'], ['forbidden duels', 'stolen grimoires', 'scholarship jealousy']],
  ['Nova Hero Institute', 'Superhero trainees build powers, teams, and public approval under constant scrutiny.', 'Near-future academy', 'Hero PR, training bravado, teamwork pressure, mission debrief energy.', ['Vanguard Track', 'Stealth Track', 'Civic PR Office'], ['failed rescues', 'power envy', 'team betrayals']],
  ['Velvet City', 'Vampire nightlife society of old money clubs, covens, and glittering grudges.', 'Nocturnal modern gothic', 'Elegant, dangerous, flirtatious; nightlife whispers and blood-oath politics.', ['The Velvet House', 'Neon Coven', 'Dawn Watchers'], ['club bans', 'feeding rumors', 'ancient exes']],
  ['Crownfall Court', 'Fantasy royal politics where every banquet toast can become a succession crisis.', 'High fantasy court', 'Formal, political, poetic; alliances hidden behind courtesy.', ['Rose Court', 'Iron Council', 'River Envoys'], ['inheritance claims', 'duel petitions', 'marriage rumors']],
  ['Neon Idol House', 'Music trainees chase debut, fanbase loyalty, and image survival.', 'Modern entertainment dorm', 'Fanbase-driven, image-conscious, polished but anxious.', ['Vocal Line', 'Dance Line', 'Fan Managers'], ['line distribution', 'dating rumors', 'practice leaks']],
  ['Metro High', 'Original high-school social drama built around clubs, hallways, and weekend rumors.', 'Modern school year', 'Teen social media, school-paper gossip, careful with age-appropriate drama.', ['Student Council', 'Theater Crew', 'Varsity Circle'], ['party invites', 'group projects', 'friendship fallout']],
  ['Underground Scene', 'Indie bands, venue politics, zines, and low-stakes fame that feels huge.', 'Modern alt music scene', 'DIY, sardonic, flyer-caption energy; not too polished.', ['Basement Bands', 'Zine Kids', 'Venue Regulars'], ['setlist theft', 'tour van rumors', 'sellout accusations']],
  ['Runway District', 'Fashion influencer world of shoots, stylists, brandless lookbooks, and rival aesthetics.', 'Modern fashion district', 'Editorial, dramatic, aesthetic-first; no real brands.', ['Atelier Row', 'Street Stylists', 'Editorial Circle'], ['copied looks', 'front-row snubs', 'portfolio leaks']],
  ['Streetball League', 'Basketball reputation world where courtside respect matters more than trophies.', 'Urban summer league', 'Competitive, reputation-based, sharp court talk without overdone slang.', ['North Court', 'Harbor Crew', 'Night Run'], ['called fouls', 'highlight clips', 'captain rivalries']],
  ['Starship Meridian', 'Sci-fi crew drama aboard a long-range vessel with factions, logs, and loyalty tests.', 'Far-future starship', 'Mission-log precise, tense, exploratory; crew chain-of-command matters.', ['Bridge Crew', 'Engineering Bay', 'Science Deck'], ['airlock rumors', 'promotion disputes', 'first-contact choices']]
];
function makeWorld([name, description, timePeriod, styleGuide, factions, dramaThemes]) {
  const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  return { id: uid('world'), name, description, timePeriod, socialMediaStyle: `${name} private social stream`, styleGuide, slangRules: styleGuide, factions, dramaThemes,
    reputationRules: 'Influence rises slowly through consistent posts, believable alliances, and earned attention. Drama can boost visibility but damages trust.',
    forbiddenToneNotes: 'Use only original fictional people, places, factions, and accounts. Avoid real celebrities, real brands, copyrighted fandoms, paywalls, monetization, and making the player universally adored.',
    characters: [character(`${pick(['Mira', 'Cassian', 'Liora', 'Jun', 'Selene'])} ${pick(['Vale', 'Noct', 'Aster', 'Rhodes'])}`, `${factions[0]} standout`, 'ambitious, observant, and hard to impress'), character(`${pick(['Riven', 'Ari', 'Sol', 'Niko', 'Vesper'])} ${pick(['Kade', 'Moon', 'Hart', 'Iris'])}`, `${factions[1]} connector`, 'charming in public, calculating in private'), character(`${pick(['Talia', 'Orin', 'Bex', 'Lyra', 'Dax'])} ${pick(['Storm', 'Quill', 'Reed', 'Lux'])}`, `${factions[2]} wildcard`, 'funny, loyal until embarrassed, and easily pulled into drama')],
    rumorAccounts: [{ id: uid('rumor'), name: `${name} After Dark`, username: `@${slug.replaceAll('-', '')}tea`, avatar: initials(`${name} rumors`) }], fanAccounts: [{ id: uid('fan'), name: `${name} Watch`, username: `@${slug.replaceAll('-', '')}watch`, avatar: initials(`${name} fans`) }], trendingTopics: [`#${name.replace(/\s/g, '')}`, `#${factions[0].replace(/\s/g, '')}`, `#${dramaThemes[0].replace(/\s/g, '')}`] };
}
const prebuiltWorlds = blueprints.map(makeWorld);
const defaultSettings = { onlyApprovedCharacters: true, allowRandomMinorCharacters: false, negativityLevel: 55, romanceAllowed: true, dramaIntensity: 'medium', slangLevel: 45, timePeriodAccuracy: true, autoGenerateFeed: false };
function seedPost(world) { const c = pick(world.characters); return { id: uid('post'), authorId: c.id, authorType: 'character', content: `${pick(['Status check:', 'Small warning:', 'For the record:'])} ${pick(world.dramaThemes)} always starts with someone pretending they are above drama.`, postType: 'Normal post', timestamp: now(), likes: 25, reposts: 4, replies: [], quotePosts: [], comments: [], impactSummary: 'Ambient world activity' }; }
function makeDefaultState() { const world = prebuiltWorlds[0]; const player = { id: uid('player'), displayName: 'Riley Ash', username: '@rileyash', bio: 'New arrival trying to build a name without losing the plot.', age: '22', pronouns: 'they/them', avatar: initials('Riley Ash'), traits: 'curious, guarded, witty', backstory: '', goals: 'Build influence, make real allies, avoid being defined by rumors.', publicImage: 'Promising newcomer', privateInsecurity: 'Being exposed as ordinary.', relationshipStyle: 'slow trust, loyal once close', stats: { ...baseStats }, currentWorldId: world.id }; return { version: 1, activeTab: 'feed', worlds: prebuiltWorlds, currentWorldId: world.id, players: [player], activePlayerId: player.id, posts: [seedPost(world), seedPost(world)], notifications: [], memories: [{ id: uid('mem'), type: 'arrival', summary: `${player.displayName} joined ${world.name} and is still mostly unknown.`, involvedCharacters: [], importance: 4, timestamp: now(), pinned: true }], dms: [], events: [], settings: defaultSettings, onboarded: false, lastSavedAt: null }; }

function simulatePostReaction(post, world, player, characters, memory, settings) {
  const visible = (settings.onlyApprovedCharacters ? characters.filter((c) => c.approved) : characters).concat(!settings.onlyApprovedCharacters && settings.allowRandomMinorCharacters ? [character('Minor Observer', 'background account', 'temporary witness', { approved: false })] : []).filter(Boolean);
  const chosen = sample(visible.length ? visible : characters, clamp(3 + Math.floor((player.stats.drama || 0) / 35), 3, 7));
  const tone = post.postType.includes('Apology') ? 'apology' : post.postType.includes('Callout') ? 'conflict' : post.postType.includes('Flirt') ? 'flirt' : post.postType.includes('Cryptic') ? 'cryptic' : 'normal';
  const characterReplies = chosen.map((c) => ({ id: uid('reply'), characterId: c.id, author: c.name, username: c.username, content: replyText(c, post, tone, world.styleGuide), sentiment: c.relationshipScore > 35 ? 'supportive' : c.relationshipScore < -15 ? 'critical' : pick(['curious', 'neutral', 'skeptical']), likes: Math.floor(Math.random() * 90) + 3 }));
  const fanTypes = ['supporter', 'hater', 'neutral observer', 'troll', 'parasocial fan', 'concerned fan', 'rumor spreader', 'defender', 'critic'];
  const fanComments = Array.from({ length: Math.floor(Math.random() * 8) + 5 }, (_, i) => ({ id: uid('fan'), author: `${pick(['velvet', 'nova', 'orbit', 'court', 'metro', 'runway'])}_${Math.floor(Math.random() * 9000)}`, type: fanTypes[i % fanTypes.length], content: fanText(fanTypes[i % fanTypes.length], player, world), likes: Math.floor(Math.random() * 40) }));
  const quotePosts = Math.random() < 0.55 ? sample(chosen, Math.random() < 0.4 ? 2 : 1).map((c) => ({ id: uid('quote'), characterId: c.id, author: c.name, username: c.username, content: pick(['Noted.', 'Interesting timing.', 'People heard this.']), likes: Math.floor(Math.random() * 120) })) : [];
  const followerDelta = clamp(Math.round((post.content.length / 24) + characterReplies.length * 5 + (tone === 'conflict' ? -10 : 12) - settings.negativityLevel / 9), -55, 120);
  const statChanges = { followers: followerDelta, reputation: tone === 'apology' ? 4 : tone === 'conflict' ? -6 : 2, drama: tone === 'conflict' ? 18 : tone === 'apology' ? -8 : 5, influence: followerDelta > 0 ? 3 : -1, charm: tone === 'flirt' ? 5 : 1, authenticity: tone === 'cryptic' ? -2 : tone === 'apology' ? 6 : 1, controversy: tone === 'conflict' ? 8 : tone === 'apology' ? -3 : 2 };
  if (settings.dramaIntensity === 'high') statChanges.drama = Math.round(statChanges.drama * 1.4); if (settings.dramaIntensity === 'low') statChanges.drama = Math.round(statChanges.drama * 0.55);
  const relationshipChanges = chosen.map((c) => ({ characterId: c.id, name: c.name, delta: c.relationshipScore < 0 && tone === 'conflict' ? -6 : tone === 'apology' ? 4 : Math.floor(Math.random() * 7) - 2, reason: `Reacted to ${post.postType.toLowerCase()}` }));
  const newMemories = [{ id: uid('mem'), type: 'post', summary: `${player.displayName} posted a ${post.postType.toLowerCase()}: “${post.content.slice(0, 120)}${post.content.length > 120 ? '…' : ''}”`, involvedCharacters: chosen.map((c) => c.id), importance: clamp(3 + Math.abs(statChanges.drama), 1, 10), timestamp: now(), pinned: false }];
  if (quotePosts.length || Math.abs(statChanges.drama) > 8) newMemories.push({ id: uid('mem'), type: 'drama', summary: `${world.name} discourse shifted after ${chosen[0]?.name || 'the crowd'} responded publicly.`, involvedCharacters: chosen.slice(0, 2).map((c) => c.id), importance: 7, timestamp: now(), pinned: false });
  const notifications = [{ id: uid('note'), type: 'replies', text: `${characterReplies.length} characters replied to your ${post.postType.toLowerCase()}.`, timestamp: now(), read: false }, { id: uid('note'), type: followerDelta >= 0 ? 'followers' : 'follower-loss', text: `${Math.abs(followerDelta)} follower${Math.abs(followerDelta) === 1 ? '' : 's'} ${followerDelta >= 0 ? 'found' : 'left'} your profile.`, timestamp: now(), read: false }];
  const possibleEvent = Math.random() < (settings.dramaIntensity === 'high' ? 0.7 : 0.45) || tone === 'conflict' ? makeEvent(world, chosen, tone) : null;
  const trendingTopics = Math.abs(statChanges.drama) > 5 || followerDelta > 30 ? sample([...world.trendingTopics, `#${player.username.replace('@', '')}Watch`, '#PrivateReceipts'], 2) : [];
  return { characterReplies, fanComments, quotePosts, statChanges, relationshipChanges, newMemories, notifications, possibleEvent, trendingTopics };
}
function replyText(c, post, tone, style) { const lines = { apology: ['Accountability only counts if the next move changes.', 'I hear the apology. I am watching the follow-through.'], conflict: ['Bold to say this publicly. Receipts tend to answer back.', 'If this is about our circle, name the stakes clearly.'], flirt: ['That sounded personal. Should people be taking notes?', 'Careful—half the timeline can read between lines.'], cryptic: ['Cryptic posts create louder rooms than honest ones.', 'Someone knows exactly what this means.'], normal: [`This fits the ${style.toLowerCase()} mood more than you know.`, 'Not everyone will get this yet, but I do.'] }; return pick(lines[tone]); }
function fanText(type, player, world) { return ({ supporter: `Let ${player.displayName} build in peace, this is actually interesting.`, hater: 'new people arrive and immediately act central lol', 'neutral observer': `Could be nothing, could be the start of a ${world.dramaThemes[0]} arc.`, troll: 'posting this and logging off would be iconic chaos', 'parasocial fan': 'I just KNOW there is a softer reason behind this.', 'concerned fan': 'Hope this does not spiral. The tone feels tense.', 'rumor spreader': 'Rumor page is going to eat this up by midnight.', defender: 'The replies are doing too much. Read the post again.', critic: 'Good concept, messy execution. Influence has to be earned.' })[type]; }
function makeEvent(world, chars, tone) { const lead = chars[0] || world.characters[0]; return { id: uid('event'), title: tone === 'conflict' ? `${lead.name} pushes back publicly` : `A ${world.factions[0]} invitation arrives`, description: tone === 'conflict' ? `${lead.name} wants the player to clarify the post before the rumor account controls the narrative.` : 'A private event could create allies, enemies, or a leak depending on how the player handles it.', choices: ['Respond calmly with context', 'Lean into the attention', 'DM the key person privately', 'Say nothing and observe'], consequences: 'Choices affect followers, drama, relationships, and permanent memory.', resolved: false }; }
function statusFromScore(score) { if (score > 75) return 'Close friend'; if (score > 55) return 'Friend'; if (score > 35) return 'Mutual'; if (score > 15) return 'Acquaintance'; if (score < -60) return 'Enemy'; if (score < -25) return 'Rival'; return 'Stranger'; }
function summarizeImpact(changes) { return Object.entries(changes).filter(([, v]) => v).map(([k, v]) => `${k} ${v > 0 ? '+' : ''}${v}`).join(' · '); }

let state; try { state = JSON.parse(localStorage.getItem(SAVE_KEY)) || makeDefaultState(); } catch { state = makeDefaultState(); }
function save() { state.lastSavedAt = now(); localStorage.setItem(SAVE_KEY, JSON.stringify(state)); }
function setState(next) { state = typeof next === 'function' ? next(state) : next; save(); render(); }
const world = () => state.worlds.find((w) => w.id === state.currentWorldId) || state.worlds[0];
const player = () => state.players.find((p) => p.id === state.activePlayerId) || state.players[0];

function layout(content) { const unread = state.notifications.filter((n) => !n.read).length; return `<div class="app-shell"><aside class="sidebar">${brand()}${nav(unread)}</aside><main class="main-panel"><header class="topbar"><div><p class="eyebrow">${esc(world().name)}</p><h1>${esc((tabs.find(([id]) => id === state.activeTab) || [,'','Feed'])[2])}</h1></div><div class="top-actions"><button data-action="manual-save">💾 Save</button><button data-action="export-save">⇩ Export</button></div></header>${content}</main><nav class="bottom-nav">${nav(unread, true)}</nav><input id="import-file" class="hidden" type="file" accept="application/json"></div>`; }
function brand() { return `<div class="brand"><div class="logo">✦</div><div><strong>StatusSim</strong><span>Unlimited private simulator</span></div></div>`; }
function nav(unread, compact = false) { return tabs.map(([id, icon, label]) => `<button data-tab="${id}" class="nav-item ${state.activeTab === id ? 'active' : ''}">${icon}${compact ? '' : `<span>${label}</span>`}${id === 'notifications' && unread ? `<b>${unread}</b>` : ''}</button>`).join(''); }
function render() { if (!state.onboarded) { renderOnboarding(); return; } const pages = { feed: renderFeed, post: renderPost, dms: renderDMs, notifications: renderNotifications, characters: renderCharacters, profile: renderProfile, memory: renderMemory, worlds: renderWorlds, settings: renderSettings }; root.innerHTML = layout(pages[state.activeTab]()); bindGlobal(); }
function renderOnboarding() { const p = player(); root.innerHTML = `<div class="onboarding"><section class="onboard-card">${brand()}<h1>Create your persona</h1><p>StatusSim uses only original fictional worlds and characters by default. No ads, coins, energy, subscriptions, or limits.</p><div class="form-grid">${field('Display name','displayName',p.displayName)}${field('Username','username',p.username)}${field('Age','age',p.age)}${field('Pronouns','pronouns',p.pronouns)}${area('Bio','bio',p.bio)}${area('Personality traits','traits',p.traits)}${area('Backstory','backstory',p.backstory)}${area('Goals','goals',p.goals)}${area('Public image','publicImage',p.publicImage)}${area('Private insecurity','privateInsecurity',p.privateInsecurity)}${area('Relationship style','relationshipStyle',p.relationshipStyle)}${field('Starting followers','followers',p.stats.followers,'number')}${field('Current reputation','reputation',p.stats.reputation,'number')}<label>Starting world<select id="on-world">${state.worlds.map((w)=>`<option value="${w.id}" ${w.id===state.currentWorldId?'selected':''}>${esc(w.name)}</option>`).join('')}</select></label><label>Avatar upload<input id="avatar-upload" type="file" accept="image/*"></label></div><button class="primary" id="enter-app">Enter StatusSim</button></section></div>`; document.getElementById('enter-app').onclick = () => { const updated = { ...p, displayName: val('displayName'), username: val('username'), age: val('age'), pronouns: val('pronouns'), bio: val('bio'), traits: val('traits'), backstory: val('backstory'), goals: val('goals'), publicImage: val('publicImage'), privateInsecurity: val('privateInsecurity'), relationshipStyle: val('relationshipStyle'), stats: { ...p.stats, followers: Number(val('followers')), reputation: Number(val('reputation')) }, currentWorldId: val('on-world'), avatar: p.avatar || initials(val('displayName')) }; setState({ ...state, onboarded: true, currentWorldId: val('on-world'), activePlayerId: updated.id, players: [updated] }); }; document.getElementById('avatar-upload').onchange = (e) => { const file = e.target.files?.[0]; if (!file) return; const r = new FileReader(); r.onload = () => { p.avatar = r.result; }; r.readAsDataURL(file); }; }
function field(label,id,value,type='text'){return `<label>${label}<input id="${id}" type="${type}" maxLength="10000" value="${esc(value)}"></label>`} function area(label,id,value){return `<label class="wide">${label}<textarea id="${id}" maxLength="10000">${esc(value)}</textarea></label>`} function val(id){return document.getElementById(id)?.value || ''}
function renderFeed() { const w = world(); return `<section class="stack"><div class="hero-card"><div><p class="eyebrow">Trending now</p><div class="chips">${w.trendingTopics.map((t)=>`<span>${esc(t)}</span>`).join('')}</div></div><button class="primary" data-action="generate-feed">⟳ Generate Feed Activity</button></div>${state.events.filter(e=>!e.resolved).map(eventCard).join('')}${state.posts.map(postCard).join('')}</section>`; }
function eventCard(e){return `<div class="event-card"><p class="eyebrow">Story event</p><h3>${esc(e.title)}</h3><p>${esc(e.description)}</p><div class="choice-grid">${e.choices.map(c=>`<button>${esc(c)}</button>`).join('')}</div></div>`}
function postCard(p){ const w=world(); const a=p.authorType==='player'?state.players.find(x=>x.id===p.authorId)||player():w.characters.find(c=>c.id===p.authorId)||w.rumorAccounts.find(r=>r.id===p.authorId)||{}; return `<article class="post-card"><div class="post-head"><img src="${esc(a.avatar||initials('unknown'))}"><div><strong>${esc(a.displayName||a.name||'Unknown')}</strong><span>${esc(a.username)} · ${new Date(p.timestamp).toLocaleString()}</span></div>${p.authorType==='player'?`<div class="post-tools"><button data-edit-post="${p.id}">Edit</button><button data-delete-post="${p.id}">🗑</button></div>`:''}</div><p class="post-content">${esc(p.content)}</p><div class="metrics"><span>♡ ${p.likes}</span><span>⟳ ${p.reposts}</span><span>☰ ${p.replies.length+p.comments.length}</span><em>${esc(p.impactSummary)}</em></div>${p.replies.length?`<div class="reply-list">${p.replies.map(r=>`<p><strong>${esc(r.author)}</strong> ${esc(r.content)}</p>`).join('')}</div>`:''}${p.comments.length?`<details><summary>${p.comments.length} fan comments</summary>${p.comments.map(c=>`<p class="fan-comment"><b>${esc(c.author)}</b> <small>${esc(c.type)}</small> ${esc(c.content)}</p>`).join('')}</details>`:''}${p.quotePosts.length?`<details open><summary>Quote posts</summary>${p.quotePosts.map(q=>`<p><b>${esc(q.author)}</b>: ${esc(q.content)}</p>`).join('')}</details>`:''}</article>`; }
function renderPost(){ const w=world(); return `<section class="compose-card"><h2>Create a post</h2><p>Responses use the central simulation engine and recent timeline memory.</p><label>Post as<select id="poster">${state.players.map(p=>`<option value="player:${p.id}">${esc(p.displayName)} (${esc(p.username)})</option>`).join('')}${w.characters.filter(c=>c.approved).map(c=>`<option value="character:${c.id}">${esc(c.name)} (${esc(c.username)})</option>`).join('')}</select></label><label>Post type<select id="post-type">${postTypes.map(t=>`<option>${t}</option>`).join('')}</select></label><textarea id="post-content" class="big-compose" maxLength="10000" placeholder="Write the post that changes the timeline..."></textarea><button class="primary" data-action="publish-post">✦ Publish and simulate reactions</button></section>`; }
function renderDMs(){ const w=world(); const target=state.activeDm || w.characters[0]?.id; const thread=state.dms.filter(m=>m.threadId===target); return `<section class="dm-layout"><div class="thread-list">${w.characters.map(c=>`<button data-dm-target="${c.id}" class="${target===c.id?'active':''}"><img src="${esc(c.avatar)}"><span>${esc(c.name)}</span></button>`).join('')}</div><div class="dm-panel"><div class="messages">${thread.map(m=>`<p class="${m.from==='player'?'me':'them'}">${esc(m.text)}</p>`).join('')}</div><div class="dm-input"><input id="dm-text" maxLength="10000" placeholder="Send a private message..."><button data-action="send-dm">➤</button></div></div></section>`; }
function renderNotifications(){return `<section class="stack"><button data-action="mark-read">Mark all read</button>${state.notifications.map(n=>`<div class="note ${n.read?'':'unread'}"><b>${esc(n.type)}</b><p>${esc(n.text)}</p><span>${new Date(n.timestamp).toLocaleString()}</span></div>`).join('')}</section>`}
function renderCharacters(){return `<section class="grid-cards">${world().characters.map(c=>`<article class="character-card"><img src="${esc(c.avatar)}"><h3>${esc(c.name)}</h3><p>${esc(c.username)} · ${esc(c.role)}</p>${meter((c.relationshipScore+100)/2,`${c.relationshipStatus} (${c.relationshipScore})`)}<dl><dt>Personality</dt><dd>${esc(c.personality)}</dd><dt>Public image</dt><dd>${esc(c.publicImage)}</dd><dt>Private insecurity</dt><dd>${esc(c.privateInsecurity)}</dd><dt>Likes</dt><dd>${esc(c.likes.join(', '))}</dd><dt>Dislikes</dt><dd>${esc(c.dislikes.join(', '))}</dd><dt>Opinion</dt><dd>${esc(c.opinionOfPlayer)}</dd><dt>Posting / DM style</dt><dd>${esc(c.postingStyle)} / ${esc(c.dmStyle)}</dd><dt>Drama triggers</dt><dd>${esc(c.dramaTriggers.join(', '))}</dd><dt>Alliances / Enemies</dt><dd>${esc((c.allies.join(', ')||'None')+' / '+(c.enemies.join(', ')||'None'))}</dd></dl><label class="toggle"><input type="checkbox" data-approve="${c.id}" ${c.approved?'checked':''}> Approved</label></article>`).join('')}</section>`}
function renderProfile(){ const p=player(), w=world(); const allies=w.characters.filter(c=>c.relationshipScore>30).slice(0,3).map(c=>c.name); const enemies=w.characters.filter(c=>c.relationshipScore<0).slice(0,3).map(c=>c.name); return `<section class="profile"><div class="profile-head"><img src="${esc(p.avatar)}"><div><h2>${esc(p.displayName)}</h2><p>${esc(p.username)} · ${esc(p.pronouns)}</p><p>${esc(p.bio)}</p></div></div><div class="stat-grid">${Object.entries(p.stats).map(([k,v])=>meter(k==='followers'?Math.min(100,v/50):v,`${k}: ${v}`)).join('')}</div><div class="columns">${info('Top allies',allies)}${info('Top enemies',enemies)}${info('Recent scandals/arcs',state.memories.filter(m=>['drama','rumor','post'].includes(m.type)).slice(0,5).map(m=>m.summary))}</div><div class="add-card"><h3>Add alternate playable persona</h3><input id="new-persona" placeholder="Display name"><button data-action="add-persona">Add persona</button></div></section>`}
function renderMemory(){return `<section class="stack">${state.memories.map(m=>`<article class="memory-card"><div><b>${m.pinned?'📌 ':''}${esc(m.type)}</b><span>${new Date(m.timestamp).toLocaleString()} · importance ${m.importance}</span></div><textarea maxLength="10000" data-memory-text="${m.id}">${esc(m.summary)}</textarea><button data-pin-memory="${m.id}">${m.pinned?'Unpin':'Pin'}</button><button data-delete-memory="${m.id}">Delete</button></article>`).join('')}</section>`}
function renderWorlds(){return `<section class="stack"><div class="grid-cards">${state.worlds.map(w=>`<article class="world-card"><h3>${esc(w.name)}</h3><p>${esc(w.description)}</p><p><b>Time:</b> ${esc(w.timePeriod)}</p><p><b>Style:</b> ${esc(w.styleGuide)}</p><p><b>Factions:</b> ${esc(w.factions.join(', '))}</p><p><b>Forbidden notes:</b> ${esc(w.forbiddenToneNotes)}</p><button data-join-world="${w.id}" class="${state.currentWorldId===w.id?'primary':''}">Join world</button></article>`).join('')}</div><div class="compose-card"><h2>Create original world</h2>${field('Name','cw-name','')}${area('Description','cw-description','')}${field('Time period','cw-time','')}${area('Language/style guide','cw-style','')}${field('Main factions (comma-separated)','cw-factions','')}${field('Drama themes (comma-separated)','cw-drama','')}<button data-action="create-world">Create world</button><button data-action="duplicate-world">Duplicate current world</button></div></section>`}
function renderSettings(){ const s=state.settings; return `<section class="settings-card"><h2>Settings and save system</h2><p class="callout">Unlimited private play: no energy, coins, gems, coffee, timers, subscriptions, ads, premium gates, post limits, DM limits, character limits, or world limits exist in this app.</p>${Object.entries(s).map(([k,v])=>typeof v==='boolean'?`<label class="toggle"><input data-setting="${k}" type="checkbox" ${v?'checked':''}>${k}</label>`:k==='dramaIntensity'?`<label>${k}<select data-setting="${k}">${['low','medium','high'].map(x=>`<option ${v===x?'selected':''}>${x}</option>`).join('')}</select></label>`:`<label>${k}<input data-setting="${k}" type="range" min="0" max="100" value="${v}"></label>`).join('')}<div class="button-row"><button data-action="manual-save">💾 Manual save</button><button data-action="export-save">⇩ Export JSON</button><button data-action="import-save">⇧ Import JSON</button><button data-action="backup-memory">▣ Backup memories</button><button class="danger" data-action="reset-all">Reset all data</button></div><p>Last saved: ${state.lastSavedAt ? new Date(state.lastSavedAt).toLocaleString() : 'Autosave pending'}</p><details><summary>Internal AI simulation prompt</summary><p>${esc(AI_SYSTEM_PROMPT)}</p></details></section>`}
function meter(value,label){return `<div class="meter"><span>${esc(label)}</span><div><i style="width:${clamp(value,0,100)}%"></i></div></div>`} function info(title,items){return `<div class="info-card"><h3>${esc(title)}</h3>${items.length?items.map(i=>`<p>${esc(i)}</p>`).join(''):'<p>None yet.</p>'}</div>`}

function bindGlobal() {
  document.querySelectorAll('[data-tab]').forEach((b)=>b.onclick=()=>setState({...state, activeTab:b.dataset.tab}));
  document.querySelector('[data-action="manual-save"]')?.addEventListener('click', save);
  document.querySelectorAll('[data-action]').forEach((b)=>b.onclick=()=>handleAction(b.dataset.action));
  document.querySelectorAll('[data-delete-post]').forEach((b)=>b.onclick=()=>setState({...state, posts:state.posts.filter(p=>p.id!==b.dataset.deletePost), memories:[{id:uid('mem'),type:'deletion',summary:`${player().displayName} deleted a post. Some people may remember it.`,involvedCharacters:[],importance:5,timestamp:now(),pinned:false},...state.memories]}));
  document.querySelectorAll('[data-edit-post]').forEach((b)=>b.onclick=()=>{ const p=state.posts.find(x=>x.id===b.dataset.editPost); const content=prompt('Edit post',p.content); if(content!==null)setState({...state,posts:state.posts.map(x=>x.id===p.id?{...x,content,impactSummary:`${x.impactSummary} · edited`}:x)}); });
  document.querySelectorAll('[data-dm-target]').forEach((b)=>b.onclick=()=>setState({...state, activeDm:b.dataset.dmTarget}));
  document.querySelectorAll('[data-approve]').forEach((i)=>i.onchange=()=>setState({...state,worlds:state.worlds.map(w=>w.id===world().id?{...w,characters:w.characters.map(c=>c.id===i.dataset.approve?{...c,approved:i.checked}:c)}:w)}));
  document.querySelectorAll('[data-memory-text]').forEach((t)=>t.onchange=()=>setState({...state,memories:state.memories.map(m=>m.id===t.dataset.memoryText?{...m,summary:t.value}:m)}));
  document.querySelectorAll('[data-pin-memory]').forEach((b)=>b.onclick=()=>setState({...state,memories:state.memories.map(m=>m.id===b.dataset.pinMemory?{...m,pinned:!m.pinned}:m)}));
  document.querySelectorAll('[data-delete-memory]').forEach((b)=>b.onclick=()=>setState({...state,memories:state.memories.filter(m=>m.id!==b.dataset.deleteMemory)}));
  document.querySelectorAll('[data-join-world]').forEach((b)=>b.onclick=()=>setState({...state,currentWorldId:b.dataset.joinWorld,players:state.players.map(p=>p.id===state.activePlayerId?{...p,currentWorldId:b.dataset.joinWorld}:p)}));
  document.querySelectorAll('[data-setting]').forEach((el)=>el.onchange=()=>setState({...state,settings:{...state.settings,[el.dataset.setting]:el.type==='checkbox'?el.checked:el.type==='range'?Number(el.value):el.value}}));
  const file=document.getElementById('import-file'); if(file) file.onchange=(e)=>{const f=e.target.files?.[0]; if(!f)return; const r=new FileReader(); r.onload=()=>{try{setState(JSON.parse(r.result))}catch{alert('Invalid save JSON.')}}; r.readAsText(f);};
}
function handleAction(action) { if(action==='generate-feed'){ const w=world(), c=pick(w.characters), topic=pick([...w.trendingTopics,...w.dramaThemes]); setState({...state,posts:[{id:uid('post'),authorId:c.id,authorType:'character',content:`${pick(['Unprompted thought:','Public note:','Before anyone twists this:'])} ${topic} is changing the room. Choose your alliances carefully.`,postType:'Normal post',timestamp:now(),likes:Math.floor(Math.random()*130),reposts:Math.floor(Math.random()*20),replies:[],quotePosts:[],comments:[],impactSummary:'Organic world activity'},...state.posts],memories:[{id:uid('mem'),type:'ambient',summary:`${c.name} posted about ${topic}.`,involvedCharacters:[c.id],importance:2,timestamp:now(),pinned:false},...state.memories]}); }
  if(action==='publish-post'){ const content=val('post-content'); if(!content.trim())return; const [authorType,authorId]=val('poster').split(':'); const post={id:uid('post'),authorId,authorType,content:content.trim(),postType:val('post-type'),timestamp:now(),likes:0,reposts:0,replies:[],quotePosts:[],comments:[],impactSummary:''}; const reaction=simulatePostReaction(post,world(),player(),world().characters,state.memories,state.settings); applyReaction(post,reaction); }
  if(action==='send-dm'){ const text=val('dm-text'); if(!text.trim())return; const w=world(), target=state.activeDm||w.characters[0]?.id, c=w.characters.find(x=>x.id===target); setState({...state,dms:[...state.dms,{id:uid('dm'),threadId:target,from:'player',text,timestamp:now()},{id:uid('dm'),threadId:target,from:c.id,text:`${c.dmStyle}. Privately, I think this changes how I read your public posts.`,timestamp:now()}],memories:[{id:uid('mem'),type:'dm',summary:`${player().displayName} privately messaged ${c.name}.`,involvedCharacters:[c.id],importance:5,timestamp:now(),pinned:false},...state.memories],notifications:[{id:uid('note'),type:'dm',text:`${c.name} replied in DMs.`,timestamp:now(),read:false},...state.notifications]}); }
  if(action==='mark-read') setState({...state,notifications:state.notifications.map(n=>({...n,read:true}))}); if(action==='add-persona'){ const name=val('new-persona'); if(name.trim())setState({...state,players:[...state.players,{id:uid('player'),displayName:name,username:`@${name.toLowerCase().replace(/[^a-z0-9]/g,'')}`,bio:'Alternate controlled persona.',age:'',pronouns:'',avatar:initials(name),traits:'',backstory:'',goals:'',publicImage:'',privateInsecurity:'',relationshipStyle:'',stats:{...baseStats,followers:80},currentWorldId:world().id}]}); }
  if(action==='create-world'){ const w=makeWorld([val('cw-name')||'Custom World',val('cw-description')||'A custom original social universe.',val('cw-time')||'Original era',val('cw-style')||'User-defined style guide.',splitList(val('cw-factions')).length?splitList(val('cw-factions')):['Main Circle','Rivals','Observers'],splitList(val('cw-drama')).length?splitList(val('cw-drama')):['rumors','alliances','public pressure']]); setState({...state,worlds:[w,...state.worlds],currentWorldId:w.id}); }
  if(action==='duplicate-world'){ const w=structuredClone(world()); w.id=uid('world'); w.name=`${w.name} Copy`; setState({...state,worlds:[w,...state.worlds]}); } if(action==='export-save') download('statussim-save.json',state); if(action==='backup-memory') download('statussim-memories.json',state.memories); if(action==='import-save') document.getElementById('import-file')?.click(); if(action==='reset-all'&&confirm('Reset all StatusSim data?')) setState(makeDefaultState()); }
function applyReaction(post,reaction){ const p={...player(),stats:{...player().stats}}; Object.entries(reaction.statChanges).forEach(([k,v])=>p.stats[k]=clamp((p.stats[k]||0)+v,0,k==='followers'?999999999:100)); const w=world(); const updatedWorld={...w,trendingTopics:[...new Set([...reaction.trendingTopics,...w.trendingTopics])].slice(0,12),characters:w.characters.map(c=>{const rel=reaction.relationshipChanges.find(r=>r.characterId===c.id); if(!rel)return c; const score=clamp(c.relationshipScore+rel.delta,-100,100); return {...c,relationshipScore:score,relationshipStatus:statusFromScore(score),opinionOfPlayer:rel.reason};})}; const fullPost={...post,replies:reaction.characterReplies,comments:reaction.fanComments,quotePosts:reaction.quotePosts,likes:Math.max(1,Math.abs(reaction.statChanges.followers)+12),reposts:reaction.quotePosts.length+Math.floor(Math.random()*12),impactSummary:summarizeImpact(reaction.statChanges)}; setState({...state,activeTab:'feed',worlds:state.worlds.map(x=>x.id===w.id?updatedWorld:x),players:state.players.map(x=>x.id===p.id?p:x),posts:[fullPost,...state.posts],memories:[...reaction.newMemories,...state.memories],notifications:[...reaction.notifications,...state.notifications],events:reaction.possibleEvent?[reaction.possibleEvent,...state.events]:state.events}); }
function download(name,data){ const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})); a.download=name; a.click(); URL.revokeObjectURL(a.href); }
render();
